# Numpy Introduction 

In [83]:
%matplotlib inline 
%run mplimp.py

ERROR:root:File `'mplimp.py'` not found.


In [38]:
import numpy as np

In [39]:
np.random.seed(1337)

#Ek baari huma ek value milgai toh dubara bhi wohi value ayegi iss "seed" se and its a good practice to set seed
#by importing the numpy

# Basics of Matrices

In [40]:
#This array of numpy is kind of similar to the array in c++ and there is a complete difference in list and numpy array.

x = np.array([1,4,3])
x


array([1, 4, 3])

In [41]:
#2D-Array 

y = np.array([[1,4,3],[9,2,7]])
y

array([[1, 4, 3],
       [9, 2, 7]])

In [42]:
x.shape #rank 1 tensor we can think about it as a row vector or column vector it behaves like both of these 

(3,)

In [43]:
y.shape # 2 rows and 3 columns inportant in machine learning

(2, 3)

In [44]:
z = np.array([[1,4,3]])

In [45]:
z.shape #one row and 3 columns and it can be called as row vector or matrix with one row 

(1, 3)

In [46]:
 z = np.arange(1,2000,1) #start, end, shape 
 z[:10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
z.shape #its a numpy library we only know that it will give 1999 ...not 20000

(1999,)

In [48]:
np.arange(0.5,10,1).shape #Why 10 ??? will ask it to sir.

(10,)

In [49]:
#Now we have a a one row vector of "10 clomuns" but we want to make it a matrix of "5 columns" and "2 rows"
np.arange(0.5,10,1).reshape(5,2).shape

(5, 2)

In [50]:
np.arange(0.5,10,1).reshape(5,3).shape
#it will through an error because elements are 10 and they cant breake into 5 columns 3 rows and

ValueError: cannot reshape array of size 10 into shape (5,3)

In [51]:
#Ye step size khud calculate karta hai hum isse bol rhae hain taht 3 se start karo and 9 tak jao and total ye 10 elements hona chahiye

a = np.linspace(3,9,10)
a

array([3.        , 3.66666667, 4.33333333, 5.        , 5.66666667,
       6.33333333, 7.        , 7.66666667, 8.33333333, 9.        ])

In [52]:
print(x)    # puri array
print(x[1]) #ist index
print(x[1:]) #ist index se last tk

[1 4 3]
4
[4 3]


In [53]:
print(y)

[[1 4 3]
 [9 2 7]]


In [54]:
 y[0,1] # "Row 0" and "column 1" 

4

In [57]:
l = y[:,1] #sari rows mn se ist index wala column lekin ye huma column vector return nhi kar raha 


In [ ]:
y[:,[1,2]] #sari rows..column number 1 and column number 2

In [ ]:
y[:,[1,2]].shape

In [58]:
np.zeros((3,5)) #"3 rows" and "5 columns" will be filed with with zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [59]:
np.ones((5,3)) #"5 rows" and "3 columns" will be filed with with ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [60]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [61]:
a.shape

(15,)

In [ ]:
a[3] = 7

In [ ]:
a

In [ ]:
a[:3] = 1 #starting se leke 2 index tk saroo ko 1 kardo

In [ ]:
a

In [ ]:
a[1:4] = [9,8,7] # ist index se leke 2nd index tk 9,8,7 daldo

In [ ]:
a

In [62]:
b = np.zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

In [63]:
b[0,0] = 1
b[0,1] = 2
b[1,0] = 3
b[1,1] = 4

In [64]:
b

array([[1., 2.],
       [3., 4.]])

In [65]:
b.shape

(2, 2)

# Array Operations 

In [66]:
print(b)

[[1. 2.]
 [3. 4.]]


In [67]:
b + 2 # 2 will be added with all the elements but it will not be saved to original.

array([[3., 4.],
       [5., 6.]])

In [68]:
b #original b

array([[1., 2.],
       [3., 4.]])

In [69]:
2*b

array([[2., 4.],
       [6., 8.]])

In [70]:
b #original b

array([[1., 2.],
       [3., 4.]])

In [71]:
b**2 #square on elements 

array([[ 1.,  4.],
       [ 9., 16.]])

In [72]:
b #original b

array([[1., 2.],
       [3., 4.]])

In [73]:
#column wise sum but this sum(b) is the function of python not the numpy array and this is bad practice if we want
# to add the row and column we will do the axis...
sum(b)

array([4., 6.])

In [74]:
b.sum() #Sum of whole matrix...original numpy array function

10.0

In [ ]:
b #original b

In [75]:
#The right way to do the sum of rows and columns

b.sum(axis=0) #Column wise sum 

array([4., 6.])

In [76]:
b.sum(axis=1) #Row wise sum

array([3., 7.])

In [77]:
b = np.array([[1,2],[3,4]]) 

In [78]:
d = np.array([[3,4],[5,6]]) 

In [79]:
b

array([[1, 2],
       [3, 4]])

In [80]:
d

array([[3, 4],
       [5, 6]])

In [81]:
b+d #Addition of two martrix

array([[ 4,  6],
       [ 8, 10]])

In [82]:
b*d #Just like the addition of matrices this also does the same element to element multiplication

array([[ 3,  8],
       [15, 24]])

In [83]:
b.dot(d) #This is the matrix multiplication that we normaly do 

array([[13, 16],
       [29, 36]])

In [84]:
b,d

(array([[1, 2],
        [3, 4]]),
 array([[3, 4],
        [5, 6]]))

In [85]:
b ** d #This means that 1^3 and  2^4  and so on..

array([[   1,   16],
       [ 243, 4096]])

In [ ]:
b.T #Transpose of the matrix

In [ ]:
a

In [ ]:
a.shape

In [ ]:
a.T

In [86]:
a.T.shape

(15,)

In [ ]:
a = a.reshape(15,1)

In [ ]:
a

In [ ]:
a.shape

In [ ]:
a  = a.T

In [ ]:
a

In [ ]:
a.shape

In [87]:
print(np.sqrt(36)) #it also works on the scalars

6.0


In [88]:
x = [1,4,9,16]
np.sqrt(x)

#Also working on Vectors

array([1., 2., 3., 4.])

In [89]:
x = np.array([1,2,4,5,9,3])
y = np.array([0,2,3,1,2,3])

In [90]:
x > 3 # example: 1 > 3 = false

array([False, False,  True,  True,  True, False])

In [100]:
x > y #element wise comparison 

array([ True, False,  True,  True,  True, False])

In [101]:
#At  "+ve infinity" it gives "1" and at "-ve infinity" it gives "0"
#And always returns the value between 0 and 1 

#Ye Function list ke upar kaam is liye nhi karta kyu k ye scalars pe define huwa para hai...and hum direct usse 
#list nhi de sakta
import math
def basic_sigmoid(x):
    """
    Compute sigmoid of x.

    Arguments:
    x -- A scalar

    Return:
    s -- sigmoid(x)
    """
    
    s = 1./(1. + math.e ** (-x))
    
    return s

In [102]:
basic_sigmoid(-1)

0.2689414213699951

In [103]:
basic_sigmoid(0)

0.5

In [91]:
x = [-1, 0, 3]
basic_sigmoid(x)

# X is a list and there is no sense in -x. If we want to pass this list then we have to convert it to "numpy array".

NameError: name 'basic_sigmoid' is not defined

# BroadCasting 

In [93]:
import numpy as np 
#Broadcasting means ek banda baat kar raha hai and bujat sara usse sun raha hain...so ek vector buhat saro ke sath add ho raha

In [94]:
x = np.array([1,2,3])

In [95]:
x*3 #This can be done in siple maths...

array([3, 6, 9])

In [96]:
x + 3 #But does this make sense ???

array([4, 5, 6])

# General Rule : Two dimensions are compatible

## They are equal, or
## one of them is 1

In [172]:
x  = np.arange(4)
xx = x.reshape(4,1) #4 rows and 1 column now this is a column vector...
y  = np.ones(5)
z  = np.ones((3,4))

In [173]:
print("x = ",x)
print("xx = ",x)
print("y = ",x)

print("Shapes: ")
print(x.shape)
print(xx.shape)
print(y.shape)

x =  [0 1 2 3]
xx =  [0 1 2 3]
y =  [0 1 2 3]
Shapes: 
(4,)
(4, 1)
(5,)


In [174]:
print(x)
x.shape

[0 1 2 3]


(4,)

In [175]:
print(y)
y.shape

[1. 1. 1. 1. 1.]


(5,)

In [176]:
x+y #This will give an error because the the both rules are not satisfying here... "x has (4,)" and "y has (5,)
#Remember ye broadcasting ki error is liye de raha hai...humne toh add karne ki koshish ki...it's coz broadcasting is so common 
#usne add karnre se pehala bradcasting ki...

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [177]:
a = np.arange(1,11,1).reshape(2,5)
b = np.arange(1,11,1).reshape(2,5)



In [178]:
print(a)
print("-----------")
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
-----------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [179]:
a+b #Row 1 elements of "a" are adding with row 1 elemnts of "b" and row 2 elements of "a" are adding with row 2 elements of "b"


array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [180]:
y.shape

(5,)

In [181]:
xx.shape

(4, 1)

In [182]:
print(y)
print(xx)


[1. 1. 1. 1. 1.]
[[0]
 [1]
 [2]
 [3]]


In [188]:
out =  y+xx # xx is broadcast over the columns of y 
#And ye isi liye kaam kar raha hai kyu jke xx ki shape (4,1) hai agar ye (4,2) hoti toh ye kaam na karta  
#Even agar ye (1,4) bhi hota phir bhi ye error deta....

In [189]:
print(out)

[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


In [190]:
out.shape

(4, 5)

In [191]:
b = np.array( [ 1.0,  2.0,  3.0  ] )  

In [192]:
b.shape

(3,)

In [194]:
a = np.array( [ 0.0, 10.0, 20.0, 30.0 ] )
b = np.array( [ 1.0, 2.0,  3.0 ]  )      

In [196]:
a+b # Error  

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [210]:
a1 = a.reshape(4,1)

In [212]:
a1

array([[ 0.],
       [10.],
       [20.],
       [30.]])

In [213]:
b

array([[1., 2., 3.]])

In [211]:
a1+b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

# Normalizing 

In [102]:
import numpy as np

In [103]:
x = np.array([[0,3,4],
                [1,6,4]])

In [104]:
x_norm = np.amax(x,axis=1)

In [105]:
print(x_norm)





[4 6]


In [106]:
x_norm.shape

(2,)

In [110]:
x / x_norm #Broadcasting Error

array([[0.        , 0.75      , 1.        ],
       [0.16666667, 1.        , 0.66666667]])

In [111]:
x_norm = x_norm.reshape(2,1)

In [112]:
x/x_norm #??????????????

array([[0.        , 0.75      , 1.        ],
       [0.16666667, 1.        , 0.66666667]])

In [31]:
# We can also use another normalization method 
x = np.array([ [ 0, 3, 4 ],
               [ 1, 6, 4 ] ])
#How is this working ???????????????????????
# no need to reshape again 
x_norm = np.linalg.norm(x, ord = 2, axis = 1, keepdims = True

SyntaxError: unexpected EOF while parsing (<ipython-input-31-8b30c00da2bc>, line 6)